#!/usr/bin/env python3
from pathlib import Path
import csv,json,statistics,random,hashlib,difflib
import torch
ROOT=Path(__file__).resolve().parents[1]
# These capture files were generated by this experiment under results/, never user-supplied pickle inputs.
torch.set_num_threads(4)
names=['fullkv','original','identity','original_context','direct1','dense1','dense3','dense7','dense1_repeat','original_repeat','identity_fixed_v2','dense1_fixed_v2','original_gen8','dense1_gen8']
rows={}
for name in names:
 p=ROOT/'results'/name/'scored_records.jsonl'
 if p.exists():rows[name]=[json.loads(x) for x in p.read_text().splitlines()]
baseline={x['uid']:x for x in rows['original']}
def mean(x):return statistics.mean(x) if x else None
def paired_ci(d):
 rng=random.Random(912);n=len(d)
 boot=sorted(sum(d[rng.randrange(n)] for _ in range(n))/n for _ in range(2000))
 return [boot[50],boot[1950]]
result=[]
for name, rs in rows.items():
 n=len(rs);t=sorted(x['ttft_ms'] for x in rs)
 d=[int(x['correct'])-int(baseline[x['uid']]['correct']) for x in rs]
 row={'variant':name,'n':n,'accuracy':mean([x['correct'] for x in rs]),
      'accuracy_delta_vs_original':mean(d),'paired_bootstrap95_delta':paired_ci(d),
      'prediction_agreement_vs_original':mean([x['prediction']==baseline[x['uid']]['prediction'] for x in rs]),
      'mean_ttft_ms':mean(t),'p95_ttft_ms':t[min(n-1,int(.95*n))],
      'mean_physical_prefetch_bytes':mean([x['physical_prefetch_kv_bytes'] for x in rs]),
      'mean_logical_selected_bytes':mean([x['selected_kv_bytes'] for x in rs]),
      'mean_ssd_read_bytes':mean([x['total_ssd_read_bytes'] for x in rs]),
      'mean_selector_bytes':mean([x['selector_key_bytes'] for x in rs]),
      'selection_agreement_vs_original':mean([x['layer_token_selection_sha256']==baseline[x['uid']]['layer_token_selection_sha256'] for x in rs])}
 # Loader source counters count K and V tensor tokens separately.
 head_bytes=4*128*2
 row['mean_host_source_payload_bytes']=mean([(x['prefetch_cpu_source_tensor_tokens']+x['prefetch_disk_source_tensor_tokens'])*head_bytes for x in rs])
 extra=ROOT/'results'/f'{name}.extra.jsonl'
 if extra.exists():
  es=[json.loads(x) for x in extra.read_text().splitlines()][-n:]
  row.update(mean_unique_selected_bytes=mean([x['unique_selected_payload_bytes_fp16'] for x in es]),
             physical_resolve_calls=sorted(set(x['physical_resolve_calls'] for x in es)),
             reader_bytes=max(x['resident_reader_bytes'] for x in es),
             prefix_buffer_bytes=max(x['request_prefix_buffer_bytes'] for x in es))
  if 'prefix_storage_ptrs_by_layer' in es[0]:
   row['physical_alias_verified']=all(all(x['prefix_storage_ptrs_by_layer'][lid]==x['prefix_storage_ptrs_by_layer'][src] for lid,src in enumerate(x['sources'])) and len(set(tuple(p) for p in x['prefix_storage_ptrs_by_layer']))==x['physical_resolve_calls'] for x in es)
  if 'query_tokens' in es[0]:
   row['private_cache_bounded']=all(all(v<=x['query_tokens']+max(x['requested_max_tokens']-1,3) for v in x['private_tail_lengths'].values()) for x in es)
 # Full-vocabulary first-token comparison on exactly the available matched queries.
 lp=ROOT/'results'/f'{name}_logits'
 kl=[];rmse=[];top=[];completions=[]
 if lp.exists():
  for p in sorted(lp.glob('*.pt')):
   bp=ROOT/'results/original_logits'/p.name
   if not bp.exists():continue
   b=torch.load(bp,weights_only=False)['logits'].float()
   saved=torch.load(p,weights_only=False);x=saved['logits'].float()
   kl.append((b.softmax(-1)*(b.log_softmax(-1)-x.log_softmax(-1))).sum().item())
   rmse.append((b-x).square().mean().sqrt().item());top.append(int(b.argmax()==x.argmax()))
   gp=ROOT/'results/original_gen8_logits'/p.name
   if name=='dense1_gen8' and gp.exists():
    old=torch.load(gp,weights_only=False)
    completions.append({'query_hash':p.stem,'original':old.get('completion'),'shared':saved.get('completion')})
  row.update(logits_compared=len(kl),mean_logits_kl=mean(kl),mean_logits_rmse=mean(rmse),greedy_agreement=mean(top))
  if completions:
   row['generation_exact_match']=mean([x['original']==x['shared'] for x in completions])
   (ROOT/'results/generation_examples.json').write_text(json.dumps(completions,indent=2,ensure_ascii=False))
 result.append(row)
(ROOT/'results/comparison.json').write_text(json.dumps(result,indent=2))
columns=sorted(set().union(*(x.keys() for x in result)))
with (ROOT/'results/comparison.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=columns);w.writeheader();w.writerows(result)
# Confirm calibration/test separation using actual trace and captured query hashes.
fit={p.stem for p in (ROOT/'runtime_data/cal_fit/trec').glob('*.pt')}
val={p.stem for p in (ROOT/'runtime_data/cal_val/trec').glob('*.pt')}
test={p.stem for p in (ROOT/'results/original_logits').glob('*.pt')}
separation={'fit':len(fit),'validation':len(val),'test':len(test),'pairwise_disjoint':not(fit&val or fit&test or val&test)}
(ROOT/'results/split_validation.json').write_text(json.dumps(separation,indent=2))
source=Path('/home/panzihang/src/prism_pans')
before=json.loads((ROOT/'audit/source_before.json').read_text())
changes=[f for f,h in before.items() if hashlib.sha256((source/f).read_bytes()).hexdigest()!=h]
(ROOT/'audit/source_integrity.json').write_text(json.dumps({'checked_files':len(before),'changed_files':changes,'unchanged':not changes},indent=2))
patch=[]
for folder in ['src','scripts','tests','configs']:
 for p in sorted((ROOT/folder).rglob('*')):
  if p.suffix not in ['.py','.sh','.json'] or '__pycache__' in p.parts:continue
  rel=p.relative_to(ROOT);op=source/rel
  try:
   old=op.read_text() if op.exists() else ''
   new=p.read_text()
  except UnicodeError:continue
  if old!=new:patch.extend(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='a/'+str(rel),tofile='b/'+str(rel)))
(ROOT/'audit/implementation.patch').write_text(''.join(patch))
print(json.dumps(result,indent=2))
print('SPLIT',separation,'SOURCE_CHANGED',changes)
